# Generated by Django 2.1.15 on 2024-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewNest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('digital', models.BooleanField(default=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
