# Generated by Django 2.1.15 on 2024-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewNest', '0002_auto_20240313_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='digital',
        ),
        migrations.AddField(
            model_name='pet',
            name='healthcondition',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
