# Generated by Django 2.1.15 on 2024-03-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewNest', '0003_auto_20240314_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='price',
        ),
    ]
